### ISSUE TITLE
OpenGraph support

### ISSUE THREAD

**Issue by jae1911** [Yellow-Dog-Man/go.resonite.com#3]
Add support for OpenGraph (https://ogp.me/) so session links show a nice embed.

Given the guidelines of the platforms being in contradiction of those of Discord and such, I think the thumbnail preview can be skipped, but having the rest of the metadata could be good.

**Comment by ProbablePrime** [comment]
Yeah this would be easy.

I'd probably include the thumbnail in the og meta-data. I understand the issues there in discord, but that isn't a reason to not support the OpenGraph correctly.

**Comment by ProbablePrime** [comment]
https://github.com/Yellow-Dog-Man/go.resonite.com/commit/42c252493d6d825d3da51d513a0b053763a62d81

Thank you!
