### ISSUE TITLE
RTF Tags aren't stripped from the page title

### ISSUE THREAD

**Issue by bredo228** [Yellow-Dog-Man/go.resonite.com#5]
Currently, RTF tags aren't stripped from the page title, so the page title is a little messy:

![Image](https://github.com/user-attachments/assets/c0c5dfa7-d383-43a1-b5a4-56b3480799cc)

It would be nice if the RTF tags were stripped and the session name was displayed.

This was originally noted by @djsime1 here: https://github.com/Yellow-Dog-Man/Resonite-Issues/issues/1295#issuecomment-2479952642

**Comment by ProbablePrime** [comment]
:3 https://github.com/Yellow-Dog-Man/go.resonite.com/commit/e924d1cccbf20ff0f380959599b187b962ce9de1

**Comment by ProbablePrime** [comment]
Fixed thanks to @jae1911 for the npm module.
